security:
  oauth2:
    client:
      clientId: 1973562382660373
      clientSecret: ef94e9aa2e1af7e3904dbc88a1a2e869
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me